### ISSUE TITLE
`get_neighbours` of log transformed `UniformIntegerHyperparameter` can hang

### ISSUE THREAD

**Issue by eddiebergman** [automl/ConfigSpace#263]
```python
from ConfigSpace import UniformIntegerHyperparameter

u = UniformIntegerHyperparameter("u", 1, 10, log=True)

rs = np.random.RandomState(3)
u.get_neighbors(3, rs)
# Hangs....
```

**Comment by mfeurer** [comment]
This is possibly related to #187.

**Comment by mfeurer** [comment]
The refactor for #187 added a check which makes the given input invalid and the output is now
```
Traceback (most recent call last):
  File "/home/feurerm/sync_dir/projects/ConfigSpace/bug263.py", line 7, in <module>
    u.get_neighbors(3, rs)
  File "ConfigSpace/hyperparameters.pyx", line 1604, in ConfigSpace.hyperparameters.UniformIntegerHyperparameter.get_neighbors
    assert 0 <= value <= 1, (
AssertionError: For get neighbors of UniformIntegerHyperparameter, the value if assumed to be in the unit-hypercube [0, 1]. If this was not the behaviour assumed, please raise a ticket on github.
```
