### ISSUE TITLE
Cannot create range-based hyperparameter with a range containing a single value

### ISSUE THREAD

**Issue by mdorier** [automl/ConfigSpace#371]
Example:

```
Integer("x", (1,1))
Float("x", [1.0, 1.0])
```

Gives the error:

```
Traceback (most recent call last):
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/hyperparameters/uniform_float.py", line 98, in __init__
    scaler = UnitScaler(f64(self.lower), f64(self.upper), log=log, dtype=f64)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 7, in __init__
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/hyperparameters/hp_components.py", line 258, in __post_init__
    raise ValueError(
ValueError: Upper bound 1.000000 must be larger than lower bound 1.000000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/api/types/float.py", line 117, in Float
    return UniformFloatHyperparameter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/hyperparameters/uniform_float.py", line 100, in __init__
    raise ValueError(f"Hyperparameter '{name}' has illegal settings") from e
ValueError: Hyperparameter 'x' has illegal settings
```

Why allowing single values?
- For consistency: a `Categorical` with a single choice is accepted, same for `OrdinalHyperparameter`.
- To avoid having to use if/else and a `Constant` when, e.g. one of the bounds is provided by a user.

My use-case is that of a program which builds a ConfigurationSpace with many parameters that can be from 1 to a max number passed as an argument by the user. If the user passes 1 for a parameter (i.e. forcing that parameter to always be 1), then I have to add a `Constance("param", 1)` to the ConfigurationSpace, otherwise I add an `Integer("param", (1, max_param_from_user))`. I have many such parameters so the `if/else` add up quickly, when they could just be `Integer("param", (1, max_param_from_user))` no matter the value.

**Comment by eddiebergman** [comment]
I'm not sure we can allow this trivially as this will lead to a lot of special case code with respect to division by `0` and in the fast sampling loops, this may slow things down quite a bit.

I will close this issue as will not be supported and advise that yes indeed, you will have to check this yourself in your own code, which I assume has to be done anyways given the fact users could also provide `max_param_from_user < 1`.

Sorry for the disappointing answer, we don't have manpower to maintain features which add a lot complexity, especially if the solution is manageable from the user end.

Thank you for the request though!

**Comment by mdorier** [comment]
In my code I have created a couple of functions: `IntegerOrConstant` and `FloatOrConstant`, which simply create a Constant if the bounds are the same. I also have a check that `max_param_from_user >= 1`.
