### ISSUE TITLE
deactivate_inactive_hyperparameters() fails

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#38]
Using the deactivate_inactive_hyperparameters() fails in the following example:

```
from ConfigSpace.io import pcs
from ConfigSpace.util import deactivate_inactive_hyperparameters

with open("/data/aad/aclib2/target_algorithms/sat/satenstein/params.pcs") as fp:
  pcs_str = fp.readlines()
  cs = pcs.read(pcs_str)

config = {'CONadaptpromwalkprob': '0', 'CONadaptwalkprob': 0, 'CONdp': '0.05', 'CONpromdp': '0.05', 'CONpromwp': '0.01', 'CONselectclause': '1', 'CONwp': '0.01', 'DLSalpha': '1.189', 'DLSc': '0.01', 'DLSmaxinc': '10', 'DLSpflat': '0.15', 'DLSps': '0.1', 'DLSrho': '0.5', 'DLSs': '0.01', 'DLSsapsthresh': '-0.1', 'DLSscoringmeasure': '1', 'DLStiebreaking': '1', 'DLSwp': '0.03', 'adaptive': '1', 'adaptivenoisescheme': '1', 'adaptiveprom': '0', 'adaptpromwalkprob': '0', 'adaptwalkprob': '0', 'c': '0.01', 'clausepen': '1', 'decreasingvariable': '3', 'dp': '0.05', 'heuristic': '2', 'novnoise': '0.5', 'performalternatenovelty': '1', 'performrandomwalk': '0', 'phi': '5', 'promdp': '0.05', 'promisinglist': '1', 'promnovnoise': '0.5', 'promphi': '5', 'promtheta': '6', 'promwp': '0.01', 'ps': '0.4', 'randomwalk': '1', 'rdp': '0.05', 'rfp': '0.01', 'rwp': '0.01', 's': '0.01', 'selectclause': '1', 'singleclause': '1', 'smoothingscheme': '1', 'tabu': '1', 'tabusearch': '0', 'theta': '6', 'tiebreaking': '1', 'updateschemepromlist': '3', 'wp': '0.01', 'wpwalk': '0.5'}

config = deactivate_inactive_hyperparameters(config,cs)
```

with the following message:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    config = deactivate_inactive_hyperparameters(config,cs)
  File "/home/lindauer/anaconda3/lib/python3.6/site-packages/ConfigSpace/util.py", line 381, in deactivate_inactive_hyperparameters
    if not condition.evaluate(configuration):
  File "/home/lindauer/anaconda3/lib/python3.6/site-packages/ConfigSpace/conditions.py", line 214, in evaluate
    "'%s'" % condition.parent.name)
ValueError: Evaluate must be called with all instanstatiated parent hyperparameters in the conjunction; you are (at least) missing 'CONadaptwalkprob'
```

I don't understand why since `CONadaptwalkprob` is part of the `config`.

**Comment by mfeurer** [comment]
SATenstein is known to currently not work due to a bug when using an equals condition and an integer. Does this error also happen for different configuration spaces?

**Comment by mfeurer** [comment]
Can this be closed now?

**Comment by mlindauer** [comment]
yes. thanks for providing the method
