### ISSUE TITLE
[question] Why not allow multiple conditions on the same parameter?

### ISSUE THREAD

**Issue by mdorier** [automl/ConfigSpace#380]
When I try to add multiple conditions that affect the same hyperparameter, ConfigSpace complains that adding multiple conditions is ambiguous. For example:

```
from ConfigSpace import ConfigurationSpace, EqualsCondition, Integer
cs = ConfigurationSpace()
cs.add(Integer("x", (1, 10), default=1))
cs.add(Integer("y", (1, 10), default=1))
cs.add(Integer("z", (1, 10), default=1))
cs.add(EqualsCondition(cs["z"], cs["x"], 3))
cs.add(EqualsCondition(cs["z"], cs["y"], 3))
```

Gives me:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/configuration_space.py", line 330, in add
    self._dag.add_condition(condition)
  File "/home/ubuntu/Code/spack/var/spack/environments/bedrock-env/.spack-env/view/lib/python3.11/site-packages/ConfigSpace/_condition_tree.py", line 681, in add_condition
    raise AmbiguousConditionError(
ConfigSpace.exceptions.AmbiguousConditionError: Adding a second parent condition for a for a hyperparameter is ambiguous and therefore forbidden. Use an `OrConjunction` or `AndConjunction` to combine conditions instead.
Already inserted: z | x == 3
New one: z | y == 3
```

I don't understand why it would be ambiguous. When adding multiple conditions, it would seem obvious to me that they are in conjunction with each other, not in disjonction (if anything, simply because conditions that affect distinct parameters are already in conjunction with each other).

More practically speaking, the reason this is annoying in my use-case is that, as part of a library, I have a function that returns a `ConfigurationSpace` for the parameters available to the library. The user then has a chance to further constrain this space by adding conditions on parameters. But some of the parameters already have some conditions attached to them by the library itself. 

As is, ConfigSpace doesn't seem to provide an API to remove a previously defined condition and add it back as part of an `AndConjunction`, or add more conditions to an existing `AndConjunction`.

**Comment by mdorier** [comment]
I edited the title to make it a feature request. I've been trying to get around this constraint in my code but it's becoming unmanageable. I really need a way to add multiple conditions to the same hyperparameter from different points in the code (which may be from potentially different libraries).

I looked at the code to see how this could be done. One way I would see this doable would be to allow adding conditions to an existing `AndConjunction` (and allow an `AndConjunction` to initially have a single subcondition -- checking that there are at least 2 conditions in the constructor right now isn't necessary, the code would work just the same with a single subcondition). But I'm not sure it's as simple as this... does the DAG need to be updated as well?

**Comment by eddiebergman** [comment]
As long as everything is put into one `AndConjunction`, the DAG part of the code shouldn't need to be touched too much. There is an outstanding issue where diamond OR conditions don't work though which is something to be aware of.

I'm not sure when I'll have time to implement, test and document this but I'm happy to review a PR if you're up for it.

The primary alternative from your code to build around this fact would be for you to _collect_ conditions from a user of your API and when it comes time to using the `ConfigurationSpace`, you would add all of the conditions into it.

**Comment by thijssnelleman** [comment]
Is this feature still desired?

**Comment by mdorier** [comment]
It would be nice. The workaround I have right now is that I defined a `ConfigurationSpace` class that wraps a `ConfigSpace.ConfigurationSpace`, offering the same `add` method but that method sets aside any condition that is being provided. Then when I am sure all the conditions have been provided, I have a `freeze` method that actually applies them, adding the necessary conjunctions. See [here](https://github.com/mochi-hpc/mochi-bedrock/blob/main/python/mochi/bedrock/config_space.py#L62). It works, but is clearly a hack, and a little difficult to debug as I need to wait until the `freeze` call to check that the conditions make sense.

**Comment by thijssnelleman** [comment]
@mdorier I've created a suggested solution in https://github.com/automl/ConfigSpace/pull/424

Basically, instead of yielding an exception, we would instead synthesise an AND conjunction based on the existing condition and the newly presented condition and add this instead of the new condition.

Please have a look and let me know if this solution would cover your issue.

**Comment by mdorier** [comment]
Yes, it would cover my issue. Thanks!
