### ISSUE TITLE
New Conditionals

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#8]
Hi,
I tried the following mini example for the new pcs format:

```
x1 real [0,10] [0]
x2 categorical {0,1,2,3,4,5,6,7,8,9,10}  [0]
x3 integer [0,10] [0]
x4 ordinal [0,10] [0]

x1 | x2 in {5,6,7,8,9,10} && x3 > 5
x4 | x1 > 0 || x3 < 1 && x4 < 1 
```
However, it complains

```
  File "/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/conditions.py", line 239, in __init__
    (child.name, value, parent.name))
ValueError: Hyperparameter 'x1' is conditional on the illegal value '5' of its parent hyperparameter 'x3'
```

@mfeurer @Krxsy do you have idea what is wrong here?

**Comment by Krxsy** [comment]
@mlindauer @mfeurer That's odd. It also happens with equality. It seems to be unrelated to the conditions per se. The UniformMixin class in hyperparameters.py seems to be the main culprit. It does not recognize values as legal. I will take a deeper look into that.

**Comment by sfalkner** [comment]
here is a mwe:

```
import ConfigSpace.io.pcs_new as pcs
s = """x1 real [0,1] [0]
x2 real [0,1] [0]
x1 | x2 > 0.5"""

pcs.read(s.split('\n'))
```
@mfeurer , could you have a look at that? It looks like there is a bug in the config space code itself. Thanks!

**Comment by mfeurer** [comment]
This is not really fixed yet, but I've fixed the error @mlindauer observed. Still, it doesn't parse yet.

**Comment by mfeurer** [comment]
Okay, there was an issue with the example from @mlindauer. The 2nd condition does not work because hyperparameter `x4` depends on a value of `x4`. 

@sfalkner thanks for the mwe. The bug was in the parser though, a type conversion was missing.

**Comment by mlindauer** [comment]
Unfortunately, my example (with a fix of the last conditional) still raises an error if I want to obtain the default configuration:

```
s = '''x1 real [0,10] [0]
   ...: x2 categorical {0,1,2,3,4,5,6,7,8,9,10}  [0]
   ...: x3 integer [0,10] [0]
   ...: x4 ordinal [0,10] [0]
   ...: 
   ...: x1 | x2 in {5,6,7,8,9,10} && x3 > 5
   ...: x4 | x1 > 0 || x3 < 1 && x1 < 1 
   ...: '''

In [8]: pcs.read(s.split('\n'))
Out[8]: 
Configuration space object:
  Hyperparameters:
    x1, Type: UniformFloat, Range: [0.0, 10.0], Default: 0.0
    x2, Type: Categorical, Choices: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, Default: 0
    x3, Type: UniformInteger, Range: [0, 10], Default: 0
    x4, Type: UniformFloat, Range: [0.0, 10.0], Default: 0.0
  Conditions:
    (x1 | x2 in {'5', '6', '7', '8', '9', '10'} && x1 | x3 > 5)
    (x4 | x1 > 0.0 || (x4 | x3 < 1 && x4 | x1 < 1.0))

In [9]: cs = pcs.read(s.split('\n'))

In [10]: cs.get_default_configuration()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-22d015900862> in <module>()
----> 1 cs.get_default_configuration()

/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/configuration_space.py in get_default_configuration(self)
    467 
    468     def get_default_configuration(self):
--> 469         return self._check_default_configuration()
    470 
    471     def _check_default_configuration(self):

/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/configuration_space.py in _check_default_configuration(self)
    485                 }
    486 
--> 487                 if not condition.evaluate(parents):
    488                     # TODO find out why a configuration is illegal!
    489                     active = False

/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/conditions.py in evaluate(self, instantiated_hyperparameters)
    169         evaluations = []
    170         for component in self.components:
--> 171             e = component.evaluate(instantiated_hyperparameters)
    172             evaluations.append(e)
    173 

/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/conditions.py in evaluate(self, instantiated_parent_hyperparameter)
    109     def evaluate(self, instantiated_parent_hyperparameter):
    110         hp_name = self.parent.name
--> 111         return self._evaluate(instantiated_parent_hyperparameter[hp_name])
    112 
    113     @abstractmethod

/home/lindauer/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.2.2-py3.5.egg/ConfigSpace/conditions.py in _evaluate(self, value)
    244                                   repr(self.value))
    245     def _evaluate(self, value):
--> 246         return value > self.value
    247 
    248 class InCondition(AbstractCondition):

TypeError: unorderable types: NoneType() > float()
```

**Comment by mfeurer** [comment]
@mlindauer Okay, I got this fixed. I'm wondering about hyperparameter x4 though. Shouldn't it rather be `x4 ordinal {0,10} [0]` instead of `x4 ordinal [0,10] [0]`. Since it currently parses, I suspect that there's one more bug.

**Comment by mlindauer** [comment]
@mfeurer 
No, it is indeed specified as 
`parameter_name ordinal {value_1, ..., value_N} [default value]`
Maybe this is not intuitive because it does not have a set semantic,
but we wanted to distinguish ordinal parameters from floats/integer parameters where the user only has to specify bounds.

**Comment by mfeurer** [comment]
Okay, you can now give it another try.

**Comment by mlindauer** [comment]
Here my next try:

import ConfigSpace.io.pcs_new as pcs

```
s = '''
x3 integer [0,10] [0]
x4 ordinal {yellow,green,red,blue} [yellow]

x4 | x3 ==  0'''
cs = pcs.read(s.split('\n'))

print(cs.get_default_configuration())
```

Output:
```
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    cs = pcs.read(s.split('\n'))
  File "/home/lindauer/git/ConfigSpace/ConfigSpace/io/pcs_new.py", line 373, in read
    normal_condition = condition_specification(child_name, element_list, configuration_space)
  File "/home/lindauer/git/ConfigSpace/ConfigSpace/io/pcs_new.py", line 181, in condition_specification
    condition = EqualsCondition(child, parent, restrictions)
  File "/home/lindauer/git/ConfigSpace/ConfigSpace/conditions.py", line 189, in __init__
    (child.name, value, parent.name))
ValueError: Hyperparameter 'x4' is conditional on the illegal value '0' of its parent hyperparameter 'x3'
```

Since x3 is an integer parameter, I would expect I can use `== 0`

**Comment by mlindauer** [comment]
Here another issue:

```
import ConfigSpace.io.pcs_new as pcs

s = '''
x3 integer [0,10] [0]
x4 ordinal {yellow,green,red,blue} [red]

x3 | x4 > yellow'''
cs = pcs.read(s.split('\n'))

print(cs.get_default_configuration())
```

Output:
```
Configuration:
  x4, Value: 'red'
```

Since `red > yellow`, I would expect that x3 is active.

**Comment by mfeurer** [comment]
First one is fixed, second one is trickier. While the hyperparameter implements a potential check for the order, it is not called by the comparison. In order for that to happen, I need to change the way condition checking is called :(

**Comment by mlindauer** [comment]
> First one is fixed

Thanks!

>  In order for that to happen, I need to change the way condition checking is called :(

Could you please be explicit about the consequences?
1. The code will slower after the change?
2. You will need a lot of time to change it?
3. ...?

**Comment by mfeurer** [comment]
Consequences:

1. it might be slower.
2. I'll ask a hiwi to do that, will maybe be done at the end of the month
3. it will work afterwards; I can explain this in more detail in person

**Comment by mfeurer** [comment]
@mlindauer I just checked your examples and they now work fine. Please check again whether this suites your needs.

**Comment by mlindauer** [comment]
I haven't found another counter-example :-)

Only, maybe the following error could be caught with a better message:
import ConfigSpace.io.pcs_new as pcs
```

s = '''
x3 integer [0,10] [0]
x3 | x3 != 4.99
'''
cs = pcs.read(s.split('\n'))
```

```
Traceback (most recent call last):
  File "example4.py", line 13, in <module>
    cs = pcs.read(s.split('\n'))
  File "/home/lindauer/git/ConfigSpace/ConfigSpace/io/pcs_new.py", line 384, in read
    normal_condition = condition_specification(child_name, element_list, configuration_space)
  File "/home/lindauer/git/ConfigSpace/ConfigSpace/io/pcs_new.py", line 189, in condition_specification
    restrictions = int(restrictions)
ValueError: invalid literal for int() with base 10: '4.99'
```

**Comment by mfeurer** [comment]
Closing this because it is already merged into the master branch.
