### ISSUE TITLE
Using two conditions for one hyperparameter

### ISSUE THREAD

**Issue by janvanrijn** [automl/ConfigSpace#96]
Is there anywhere documentation or examples how to do this? Currently I am getting the following error:

```
Traceback (most recent call last):
  File "/home/janvanrijn/projects/sklearn-bot/examples/run_on_study.py", line 54, in <module>
    run()
  File "/home/janvanrijn/projects/sklearn-bot/examples/run_on_study.py", line 38, in run
    configuration_space = sklearnbot.config_spaces.get_config_space(args.classifier_name, None)
  File "/home/janvanrijn/projects/sklearn-bot/sklearnbot/config_spaces/bootstrap.py", line 46, in get_config_space
    return getattr(sklearnbot.config_spaces, classifier_name).get_hyperparameter_search_space(seed)
  File "/home/janvanrijn/projects/sklearn-bot/sklearnbot/config_spaces/neural_network.py", line 104, in get_hyperparameter_search_space
    cs.add_condition(nesterovs_momentum_confition_momentum)
  File "ConfigSpace/configuration_space.py", line 187, in ConfigSpace.configuration_space.ConfigurationSpace.add_condition
  File "ConfigSpace/configuration_space.py", line 273, in ConfigSpace.configuration_space.ConfigurationSpace._check_condition
ValueError: Adding a second condition (different) for a hyperparameter is ambigouos and therefore forbidden. Add a conjunction instead!
Already inserted: mlpclassifier__nesterovs_momentum | mlpclassifier__solver == 'sgd'
New one: mlpclassifier__nesterovs_momentum | mlpclassifier__momentum > 0
```

**Comment by janvanrijn** [comment]
this seems to work:

```
nesterovs_momentum_conjunstion = ConfigSpace.AndConjunction(nesterovs_momentum_confition_solver,
                                                            nesterovs_momentum_confition_momentum)
```
